### ISSUE TITLE
BGC0001915: typo in DOI

### ISSUE THREAD

**Issue by jorgecnavarrom** [mibig-secmet/mibig-json#106]
**Affected BGC**
BGC0001915

**Describe the error**
Second reference's DOI should be **10.1016/j.tetlet.2018.02.022** instead of '10.1016/j.tetlet.2018.02.02'

**Comment by zdk123** [comment]
Already fixed in #25, fyi

**Comment by jorgecnavarrom** [comment]
Ah, you're right! Should've searched first. Thank you!
