### ISSUE TITLE
Error with BGC0001773

### ISSUE THREAD

**Issue by evanarnam** [mibig-secmet/mibig-json#12]
**Affected BGC**
Please give the BGC number of the affected cluster (e.g. BGC1234567).
BGC 0001773

**Describe the error**
2 genes are missing from the cluster: selE and selDIII. Both are just beyond the current boundary of the cluster at selI. With these additions the pathway is complete.

**Comment by kblin** [comment]
Thanks, we'll look into this for our next update.
