### ISSUE TITLE
BGC0000246 is an exact fragment of BGC0000247 (mithramycin)

### ISSUE THREAD

**Issue by althonos** [mibig-secmet/mibig-json#121]
**Affected BGC: [BGC0000246](https://mibig.secondarymetabolites.org/repository/BGC0000246/#r1c1), [BGC0000247](https://mibig.secondarymetabolites.org/repository/BGC0000247/#r1c1)**

**Describe the error**
BGC0000246 contains a subset of the genes from BGC0000247. The GenBank entry backing BGC0000246 ([AJ007932.2](https://www.ncbi.nlm.nih.gov/nuccore/AJ007932.2)) has been removed and replaced by the one backing BGC0000247. I believe BGC0000246 only contains the genes identified in the 1999 paper, and BGC0000247 contains all the genes from the `mithramycin` BGC, as reported in the 2001 paper, so BGC0000246 should be removed.

**Comment by zreitz** [comment]
Please close - BGC0000246 was retired in v3.1

**Comment by althonos** [comment]
Happy holidays @zreitz 🎅

**Comment by zreitz** [comment]
Happy holidays! Fixing MIBiG is the most entertaining activity at my in-laws' place
