### ISSUE TITLE
Error with BGC0001978 (burnettramic acid)

### ISSUE THREAD

**Issue by jorgecnavarrom** [mibig-secmet/mibig-json#128]
**Affected BGC**
BGC0001978

**Describe the error**
This entry is a duplicate of [BGC0001857](https://mibig.secondarymetabolites.org/repository/BGC0001857/index.html#r1c1)

**Comment by althonos** [comment]
On that note: BGC0001978 has the correct type (Polyketide/NRP), BGC0001857 is listed as a Polyketide/Alkaloid, however the synthesis of the pyrrolizidinedione moiety starts from L-proline. I may be wrong, but in general MIBiG doesn't seem to list proline-derived compounds as Alkaloids.
