### ISSUE TITLE
BGC0001854 (tricholignan A) is an exact duplicate of BGC0001901

### ISSUE THREAD

**Issue by althonos** [mibig-secmet/mibig-json#163]
**Affected BGC: [BGC0001854](https://mibig.secondarymetabolites.org/repository/BGC0001854/index.html#r1c1), [BGC0001901](https://mibig.secondarymetabolites.org/repository/BGC0001901/index.html#r1c1)**

**Describe the error**
- BGC0001854 is an exact duplicate of BGC0001901. Both are coming from the same GenBank record, with slightly different coordinates. In particular, BGC0001854 is missing the first gene, which is a transporter.
- The cluster is missing the gene coordinates for *tlnI*, a transcription factor.
- The genes should be marked with their names in the *tln* cluster, as shown in Fig.1 of the reference paper:
  
  ![image](https://user-images.githubusercontent.com/8660647/145427964-6d100de7-e2a0-42be-a49e-caeb92f316b0.png)

- *tlnD* and *tlnE* should be marked as "additional biosynthetic genes" since they encode enzymes that are required for maturation of the intermediate polyketide produced by the Type-I PKS encoded by *tlnA*.
- Remaining annotations from BGC0001854 should be copied to BGC0001901 (chemical activity, Polyketide subclass, etc.)

**Comment by althonos** [comment]
I added `tricholignan A` to CHEBI, so it can be used as a cross-reference and source for the compound structure: [CHEBI:188154](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI%3A188154). SMILES for this product is:
```
C=1(C(=C(C=C(C1O)O)OC)C)/C=C/C=C/C
```

**Comment by SJShaw** [comment]
BGC0001901 has been retired in 9bbb987240ae3c581ad5daa4b899ad56b136de8a
