### ISSUE TITLE
Error with BGC0001003

### ISSUE THREAD

**Issue by TylerBackman** [mibig-secmet/mibig-json#200]
**Affected BGC**
BGC0001003

**Describe the error**
The species for this is incorrect. It should be Streptomyces aureofaciens Tü117, not Kitasatospora aureofaciens.

**Comment by zreitz** [comment]
Kitasatospora aureofaciens is currently the correct name:
https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=1894

Please close this issue.
