### ISSUE TITLE
Error with BGC0000336

### ISSUE THREAD

**Issue by ReynaldoVien** [mibig-secmet/mibig-json#242]
**Affected BGC**
BGC0000336

**Describe the error**
It´s impossible to download the daptomycin gene bank file, it works for other clusters but for the BGC0000336 cluster not
![image](https://user-images.githubusercontent.com/113455400/190442505-5e53db0a-56c5-44b3-8d79-d29710841fa3.png)
[error MIBIG.pdf](https://github.com/mibig-secmet/mibig-json/files/9576605/error.MIBIG.pdf)

**Comment by SJShaw** [comment]
The link shown hasn't existed on the page for 336 since your previous issue was closed. Refresh the page, then follow the updated link.

**Comment by SJShaw** [comment]
That page was changed about 18 hours ago. It no longer has an invalid link to the genbank.

Refresh the page to get the updated version with the correct link to the genbank. It will not have a `.1` in the link, unlike the one you showed in your image.
