### ISSUE TITLE
Error with BGC0000932 and BGC0001362

### ISSUE THREAD

**Issue by esonnenschein** [mibig-secmet/mibig-json#39]
**Affected BGC**
BGC0000932 and BGC0001362

**Describe the error**
double entry of the tropodithietic acid biosynthetic gene cluster from Phaeobacter inhibens DSM 17395; could the entries be merged as they contain different information?
Thanks, Eva

**Comment by kblin** [comment]
Core genes are PGA1_262p00980 - PGA1_262p00940, PGA1_262p00810,  and PGA1_262p00800

**Comment by SJShaw** [comment]
BGC0001362's annotations were merged into BGC0000932 in a021923e52d1f92633eaf9ddf2e11d98943b8e1e and BGC0001362 was retired in f97e66268180e144b9e871053e17e4c14fa906de
