### ISSUE TITLE
BGC0000625 (thioviridamide) contains unrelated flanking genes

### ISSUE THREAD

**Issue by althonos** [mibig-secmet/mibig-json#57]
**Affected BGC: BGC0000625**

The MIBiG entry uses the same genomic sequence that is described in the reference paper, including the flanking genes `orf1-4`:
![cluster](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3811549/bin/zam9991048550002.jpg)

However, the authors exclude these flanking genes from what they consider the cluster:
> The cluster contained 10 genes arranged as an operon (tvaC-tvaL) downstream of a putative regulatory gene (the tvaB gene). **Two presumably cotranscribed genes (orf1 and orf2) upstream of the tvaA gene were excluded from the cluster** based on high homology to a DNA polymerase and a protease, respectively (Table 1). **A putative DNA polymerase gene (orf4) was also excluded**, although assignments of four genes between the tvaL and orf4 genes were unclear. To identify genes required for thioviridamide biosynthesis and the biosynthesis gene cluster, the candidate genes were cloned and expressed in Streptomyces lividans to produce thioviridamide.

They also show the production of thioviridamide without these flanking genes, using only the genes from `tvaA` to `tvaO`:
> A cosmid clone (pWE15TVAC4) contained a 14.5-kbp fragment from the tvaB gene to the tvaO gene. [...] A 14.5-kbp EcoRI fragment of pWE15TVAC4 was ligated into EcoRI-digested pBS-TVA. [...] The expression plasmid passaged through E. coli JM110 was introduced into S. lividans TK23. [...]  A UV absorption peak for thioviridamide at 274 nm was detected at a retention time of 12.4 min [...] thereby showing that the `tva` gene cluster **(`tvaA` to `tvaO`)** is responsible for thioviridamide production.

**Comment by SJShaw** [comment]
Fixed in eeeb1b9672495d2910fd7f76aa2586215b623137
