### ISSUE TITLE
BGC0000758 (capsular polysaccharide) contains unrelated flanking genes

### ISSUE THREAD

**Issue by althonos** [mibig-secmet/mibig-json#59]
**Affected BGC: BGC0000758**

The reference paper ([*Sequence analysis and molecular characterization of genes required for the biosynthesis of type 1 capsular polysaccharide in Staphylococcus aureus*, Lin et al.](https://pubmed.ncbi.nlm.nih.gov/7961465/)) for that cluster shows that the capsular polysaccharide synthesis cluster is contained in th 14.6-kb fragment containing genes from `cap1A` to `cap1O`. However, the NCBI GenBank loci record contains additional flanking regions (including a DNA Pol-I ...) that should not be included in there. The cluster coordinates should be reduced to the core region.

**Comment by SJShaw** [comment]
Fixed in e86741b2b853f646ddba201da704015c71fc741e
