### ISSUE TITLE
Error with BGC0000450

### ISSUE THREAD

**Issue by cdfage** [mibig-secmet/mibig-json#63]
**Affected BGC**
BGC0000450

**Describe the error**
As you can see in the attached image, the antiSMASH diagram for NRPS/PKS domains is not displaying correctly
![BGC0000450](https://user-images.githubusercontent.com/74153813/98482377-ddb27c00-21f8-11eb-8585-25483f0b83d6.png)

**Comment by kblin** [comment]
In addition to not drawing the SVG for some reason, it looks like the ID on the second NRPS ORF is a protein sequence?

**Comment by kblin** [comment]
Thanks for reporting this, we'll look into fixing this for the next release.

**Comment by cdfage** [comment]
> In addition to not drawing the SVG for some reason, it looks like the ID on the second NRPS ORF is a protein sequence?

Yes, that's right. Quite odd. Thanks for correcting it!

**Comment by SJShaw** [comment]
The ID is how the gene is annotated via [NCBI](https://www.ncbi.nlm.nih.gov/nuccore/AB366635.1), which is a little harder to manage, but the domain drawing should be better.
```
     CDS             complement(13608..21665)
                     /gene="MIPLSYAQRRMWFINRFEGPSSTYNIPLLLRFHGSLDTAALRAAFQDVLV"
                     /codon_start=1
                     /transl_table=11
                     /product="trsJ"
                     /protein_id="BAH04162.1"
```

**Comment by cdfage** [comment]
Okay, thanks for the information!

Best,
Chris

**Comment by kblin** [comment]
It looks like the gene name is the start of the translation of the `trsI` gene right in front of it. Unfortunately, there's no good way to report GenBank errors to NCBI.

**Comment by SJShaw** [comment]
I'm closing this as the gene identifier isn't an issue we can solve and the NRPS/PKS domain drawing is solved for future versions but isn't relevant to this repository.
