### ISSUE TITLE
Several issues with PNA BGCs characterized by Romo et al.

### ISSUE THREAD

**Issue by althonos** [mibig-secmet/mibig-json#75]
**Affected BGCs: [BGC0001956](https://mibig.secondarymetabolites.org/repository/BGC0001956/index.html#r1c1), [BGC0001957](https://mibig.secondarymetabolites.org/repository/BGC0001957/index.html#r1c1), [BGC0001958](https://mibig.secondarymetabolites.org/repository/BGC0001958/index.html#r1c1)**

## Duplicate BGCs

BGC0001957 and BGC0001958 are straight duplicates, they refer to the same locus. BGC0001958 should be removed, since it is the one with the wrong biosynthetic class assignment.

## Additional reference link

BGC0001957 and BGC0001956 reference DOI is broken (the last digit was chopped). It should be [PMID:31150226](https://pubmed.ncbi.nlm.nih.gov/31150226/).

 BGC0001957 should also receive the reference from BGC0001958:

> [Identification of the Amipurimycin Gene Cluster Yields Insight intothe Biosynthesis of C9 Sugar Nucleoside Antibiotics. Wen-Jia Kang, Hai-Xue Pan, Shengyang Wang, Biao Yu, Huiming Hua, and Gong-Li Tang. PMID: 30990701](https://pubmed.ncbi.nlm.nih.gov/30990701/)

### Amipurimycin

BGC0001957 product is missing a structure. It should be:
```
C1CC(C(C1)N)C(=O)NC(C2CC(C(C(O2)N3C=NC4=CN=C(N=C43)N)O)(C(CO)O)O)C(=O)O
```
(source: [PubChem](https://pubchem.ncbi.nlm.nih.gov/compound/Amipurimycin#section=MeSH-Tree))

### Miharamycins

BGC0001956 actually has two products according to the paper: 

- Miharamycin A
  ```
  C1C(C2(C(C(OC(C2O1)N3C=NC4=CN=C(N=C43)N)C(C(=O)O)NC(=O)C(CCCN(C(=N)N)O)N)O)O)O
  ```
  (source: [PubChem](https://pubchem.ncbi.nlm.nih.gov/compound/101015779))
- Miharamycin B:
  ```
  C1C(C2(C(C(OC(C2O1)N3C=NC4=CN=C(N=C43)N)C(C(=O)O)NC(=O)C(CCCN=C(N)N)N)O)O)O
  ```
  (source: [PubChem](https://pubchem.ncbi.nlm.nih.gov/compound/202590#section=IUPAC-Name))

**Comment by kblin** [comment]
Also BGC0001957 and BGC0001958 are the exact same cluster, and one should be discarded.
